const fs = require('fs');
const path = 'c:/Users/hoang/OneDrive/Desktop/cinima/.kiro/specs/multi-branch-cinema/design.md';
let s = fs.readFileSync(path, 'utf8');

s = s.replace('        AuthC[AuthController]\n        BranchC[BranchController]', '        AuthC[AuthController]\n        AccessC[AccessAssignmentController]\n        BranchC[BranchController]');
s = s.replace('        BranchDAO\n        MovieDAO', '        UserAccountDAO\n        RoleDAO\n        StaffBranchAssignmentDAO\n        CustomerProfileDAO\n        BranchDAO\n        MovieDAO');
s = s.replace('│   │   ├── UserDAO.java\n│   │   └── User.java', '│   │   ├── UserDAO.java                 # Tài khoản dùng chung cho 4 role đăng nhập\n│   │   ├── RoleDAO.java                 # Danh mục ADMIN/MANAGER/STAFF/CUSTOMER\n│   │   ├── StaffBranchAssignmentDAO.java # Phạm vi branch hiệu lực\n│   │   └── User.java / Role.java / StaffBranchAssignment.java / CustomerProfile.java');
s = s.replace('| AuthFilter + AuthService | Filter/Service | Xác thực session, đăng nhập/đăng ký, giới hạn sai mật khẩu | 13.2, 16.1–16.4 | UserDAO (P0), DBUtil (P0) | Service |', '| AuthFilter + AuthService | Filter/Service | Xác thực tài khoản dùng chung, đăng ký Customer, giới hạn sai mật khẩu | 13.2, 16.1–16.4 | UserDAO/RoleDAO/CustomerProfileDAO (P0), DBUtil (P0) | Service |\n| AccessAssignmentService | Service | Gán role và branch scope hiệu lực cho Branch Manager/Branch Staff | 13.1, 13.4–13.6 | UserDAO, RoleDAO, StaffBranchAssignmentDAO (P0) | Service, API |');
s = s.replace('| Dependencies | Inbound: EncodingFilter — thứ tự chain (P0). Outbound: UserDAO — tra user/role/scope (P0) |', '| Dependencies | Inbound: EncodingFilter — thứ tự chain (P0). Outbound: UserDAO/RoleDAO/StaffBranchAssignmentDAO — tra tài khoản, role và scope hiệu lực (P0) |');
const oldFilter = '- `AuthFilter.doFilter`: nếu URL yêu cầu auth mà thiếu session → redirect `/auth/login` hoặc 401 cho AJAX; kiểm tra khóa tạm thời 5 lần sai/15 phút.\n- `BranchScopeRBACFilter.doFilter`: đọc `session.user.role` + `branchId` → gắn `request.attribute("branchScope")`; chặn nếu thao tác vượt scope; ghi audit cho truy cập trái phép.';
const newFilter = '- `AuthFilter.doFilter`: Guest không có account; URL yêu cầu xác thực khi thiếu session sẽ redirect `/auth/login` hoặc trả 401 cho AJAX. Session lưu userId; role và scope hiệu lực được tra lại theo request. Kiểm tra khóa tạm thời 5 lần sai/15 phút.\n- `BranchScopeRBACFilter.doFilter`: đọc role của `user_account` và các `staff_branch_assignment` đang ACTIVE. Admin có scope toàn chuỗi; Branch Manager/Branch Staff chỉ có branch được gán; Customer chỉ có dữ liệu sở hữu. Filter gắn `request.attribute("branchScopes")`, chặn scope sai và audit truy cập trái phép.';
s = s.replace(oldFilter, newFilter);
const marker = '\n### BranchService\n';
const section = '\n### AuthService & AccessAssignmentService\n\n| Field | Detail |\n|-------|--------|\n| Intent | Cung cấp danh tính xác thực chung và quản lý role/phạm vi chi nhánh có hiệu lực |\n| Requirements | 13.1–13.6, 16.1–16.7 |\n| Dependencies | Outbound: UserDAO, RoleDAO, CustomerProfileDAO, StaffBranchAssignmentDAO (P0) |\n\n**Responsibilities & Constraints**\n- Guest là actor ẩn danh, không có hàng dữ liệu hay session xác thực.\n- `user_account` là nguồn xác thực duy nhất cho Admin, Branch Manager, Branch Staff và Customer.\n- Khi đăng ký, AuthService tạo `user_account` với role `CUSTOMER` và `customer_profile` 1:1 trong cùng transaction.\n- AccessAssignmentService chỉ cho Admin tạo/kết thúc assignment cho Branch Manager và Branch Staff. Filter tra assignment ACTIVE ở mỗi request nên thay đổi scope có hiệu lực với request kế tiếp.\n- Branch Manager/Branch Staff phải có ít nhất một assignment ACTIVE để vận hành dữ liệu branch; Customer và Admin không có staff assignment.\n\n**Contracts**: Service [x] / API [x] / State [x]\n\n##### Service Interface\n\`\`\`java\ninterface AuthService {\n  AuthenticatedUser registerCustomer(CustomerRegistrationInput input) throws ValidationException, ConflictException;\n  AuthenticatedUser login(LoginInput input) throws AuthenticationException, AccountLockedException;\n  void updateCustomerProfile(long userId, CustomerProfileInput input) throws ValidationException, ConflictException;\n}\ninterface AccessAssignmentService {\n  StaffBranchAssignment assign(long userId, long branchId, long actorAdminId) throws ValidationException, ConflictException;\n  void endAssignment(long assignmentId, long actorAdminId) throws ConflictException;\n  AccessScope resolveCurrentScope(long userId);\n}\n\`\`\`\n- Preconditions: email/phone unique trong `user_account`; assignment chỉ hợp lệ cho role Branch Manager hoặc Branch Staff và branch ACTIVE.\n- Postconditions: login tạo session có userId/role; Customer có profile 1:1; assignment mới áp dụng ở request kế tiếp.\n- Invariants: Admin có role ADMIN; Customer chỉ xem/sửa dữ liệu của mình; Guest không qua protected endpoint.\n\n##### API Contract\n| Method | Endpoint | Request | Response | Errors |\n|--------|----------|---------|----------|--------|\n| POST | /auth/register | CustomerRegistrationForm | session + redirect | 400, 409 |\n| POST | /auth/login | LoginForm | session + role landing page | 401, 423 |\n| POST | /access/assignment/create | userId, branchId | active assignment | 400, 403, 409 |\n| POST | /access/assignment/end | assignmentId | inactive assignment | 403, 409 |\n\n';
if (!s.includes('### AuthService & AccessAssignmentService')) s = s.replace(marker, section + marker);
const oldSchema = 'customer(id BIGINT IDENTITY PRIMARY KEY, email NVARCHAR(100) NOT NULL UNIQUE, phone VARCHAR(20) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, full_name NVARCHAR(100) NOT NULL, points INT NOT NULL DEFAULT 0, tier NVARCHAR(50) NOT NULL DEFAULT N\'STANDARD\', status VARCHAR(20) NOT NULL CHECK (status IN (\'ACTIVE\',\'LOCKED\')), version INT NOT NULL DEFAULT 0, created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());\nwallet(user_id BIGINT PRIMARY KEY FOREIGN KEY REFERENCES customer(id), balance BIGINT NOT NULL DEFAULT 0, version INT NOT NULL DEFAULT 0);\nwallet_tx(id BIGINT IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL FOREIGN KEY REFERENCES customer(id), type VARCHAR(20) NOT NULL CHECK (type IN (\'TOPUP\',\'SPEND\',\'REFUND\')), amount BIGINT NOT NULL CHECK (amount > 0), balance_after BIGINT NOT NULL CHECK (balance_after >= 0), ref_type VARCHAR(50) NULL, ref_id BIGINT NULL, created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());\nloyalty_config(id BIGINT IDENTITY PRIMARY KEY, tier_name NVARCHAR(50) NOT NULL UNIQUE, min_points INT NOT NULL CHECK (min_points >= 0), discount_percent INT NOT NULL CHECK (discount_percent BETWEEN 0 AND 100));\npoint_ledger(id BIGINT IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL FOREIGN KEY REFERENCES customer(id), delta INT NOT NULL, balance_after INT NOT NULL, ref_type VARCHAR(50) NULL, ref_id BIGINT NULL, created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());';
const newSchema = 'role(code VARCHAR(30) PRIMARY KEY CHECK (code IN (\'ADMIN\',\'BRANCH_MANAGER\',\'BRANCH_STAFF\',\'CUSTOMER\')), display_name NVARCHAR(50) NOT NULL UNIQUE);\nuser_account(id BIGINT IDENTITY PRIMARY KEY, email NVARCHAR(100) NOT NULL UNIQUE, phone VARCHAR(20) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, full_name NVARCHAR(100) NOT NULL, role_code VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES role(code), status VARCHAR(20) NOT NULL CHECK (status IN (\'ACTIVE\',\'LOCKED\',\'INACTIVE\')), failed_login_count INT NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0), locked_until DATETIME2(3) NULL, last_login_at DATETIME2(3) NULL, version INT NOT NULL DEFAULT 0, created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());\ncustomer_profile(user_id BIGINT PRIMARY KEY FOREIGN KEY REFERENCES user_account(id), points INT NOT NULL DEFAULT 0, tier NVARCHAR(50) NOT NULL DEFAULT N\'STANDARD\');\nstaff_branch_assignment(id BIGINT IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL FOREIGN KEY REFERENCES user_account(id), branch_id BIGINT NOT NULL FOREIGN KEY REFERENCES branch(id), effective_from DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(), effective_to DATETIME2(3) NULL, status VARCHAR(20) NOT NULL CHECK (status IN (\'ACTIVE\',\'ENDED\')), assigned_by BIGINT NOT NULL FOREIGN KEY REFERENCES user_account(id), created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_staff_branch_effective UNIQUE(user_id, branch_id, effective_from));\nwallet(user_id BIGINT PRIMARY KEY FOREIGN KEY REFERENCES customer_profile(user_id), balance BIGINT NOT NULL DEFAULT 0 CHECK (balance >= 0), version INT NOT NULL DEFAULT 0);\nwallet_tx(id BIGINT IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL FOREIGN KEY REFERENCES customer_profile(user_id), type VARCHAR(20) NOT NULL CHECK (type IN (\'TOPUP\',\'SPEND\',\'REFUND\')), amount BIGINT NOT NULL CHECK (amount > 0), balance_after BIGINT NOT NULL CHECK (balance_after >= 0), ref_type VARCHAR(50) NULL, ref_id BIGINT NULL, created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());\nloyalty_config(id BIGINT IDENTITY PRIMARY KEY, tier_name NVARCHAR(50) NOT NULL UNIQUE, min_points INT NOT NULL CHECK (min_points >= 0), discount_percent INT NOT NULL CHECK (discount_percent BETWEEN 0 AND 100));\npoint_ledger(id BIGINT IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL FOREIGN KEY REFERENCES customer_profile(user_id), delta INT NOT NULL, balance_after INT NOT NULL, ref_type VARCHAR(50) NULL, ref_id BIGINT NULL, created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());';
if (!s.includes('user_account(id BIGINT IDENTITY')) {
  if (!s.includes(oldSchema)) throw new Error('Expected old identity schema not found');
  s = s.replace(oldSchema, newSchema);
}
s = s.replace('user_id BIGINT NULL FOREIGN KEY REFERENCES customer(id)', 'user_id BIGINT NULL FOREIGN KEY REFERENCES user_account(id)');
s = s.replace('user_id BIGINT NULL FOREIGN KEY REFERENCES customer(id)', 'user_id BIGINT NULL FOREIGN KEY REFERENCES user_account(id)');
s = s.replace('user_id BIGINT NULL FOREIGN KEY REFERENCES customer(id)', 'user_id BIGINT NULL FOREIGN KEY REFERENCES user_account(id)');
s = s.replace('user_id BIGINT NULL FOREIGN KEY REFERENCES customer(id)', 'user_id BIGINT NULL FOREIGN KEY REFERENCES user_account(id)');
s = s.replace('staff_id BIGINT NOT NULL, status', 'staff_id BIGINT NOT NULL FOREIGN KEY REFERENCES user_account(id), status');
s = s.replace('approved_by BIGINT NULL);', 'approved_by BIGINT NULL FOREIGN KEY REFERENCES user_account(id));');
s = s.replace('user_id BIGINT NOT NULL FOREIGN KEY REFERENCES customer(id)', 'user_id BIGINT NOT NULL FOREIGN KEY REFERENCES user_account(id)');
s = s.replace('actor_id BIGINT NULL,', 'actor_id BIGINT NULL FOREIGN KEY REFERENCES user_account(id),');
s = s.replace('- **Aggregates**: Branch, Movie, Screen (→ Seats), Showtime, Ticket+SeatHold+Payment, Voucher, Product→Combo, BranchInventory, ConcessionOrder, Customer→Wallet/Points, Shift, Notification.', '- **Aggregates**: UserAccount (→ Role; CustomerProfile hoặc StaffBranchAssignment), Branch, Movie, Screen (→ Seats), Showtime, Ticket+SeatHold+Payment, Voucher, Product→Combo, BranchInventory, ConcessionOrder, CustomerProfile→Wallet/Points, Shift, Notification.');
s = s.replace('- Quan hệ chính: Branch 1—N Screen, Screen 1—N Seat, Showtime N—1 Movie+Screen, Showtime 1—N ShowtimeSeat status, Ticket N—1 Showtime + N—N Seat, ConcessionOrder 1—N OrderLine, Shift 1—N Payment/ConcessionOrder (gán ca).', '- Quan hệ chính: Role 1—N UserAccount; UserAccount 1—0..1 CustomerProfile; UserAccount 1—N StaffBranchAssignment; Branch 1—N StaffBranchAssignment; Branch 1—N Screen, Screen 1—N Seat, Showtime N—1 Movie+Screen, Showtime 1—N ShowtimeSeat status, Ticket N—1 Showtime + N—N Seat, ConcessionOrder 1—N OrderLine, Shift N—1 UserAccount.');
s = s.replace('customer_profile(user_id BIGINT PRIMARY KEY FOREIGN KEY REFERENCES user_account(id)', 'customer_profile(user_id BIGINT PRIMARY KEY FOREIGN KEY REFERENCES user_account(id)');
fs.writeFileSync(path, s);
console.log('design.md updated');

const rpath = 'c:/Users/hoang/OneDrive/Desktop/cinima/.kiro/specs/multi-branch-cinema/research.md';
let r = fs.readFileSync(rpath, 'utf8');
if (!r.includes('### Decision: User Account thống nhất')) {
  r = r.replace('\n### Decision: Không xây engine giảm giá hợp nhất', '\n### Decision: User Account thống nhất và Staff Branch Assignment hiệu lực\n- **Context**: Schema cần hỗ trợ 5 role: Admin, Branch Manager, Branch Staff, Customer, Guest và Req 13.\n- **Selected Approach**: `user_account` dùng chung cho bốn role đăng nhập; `role` lưu danh mục role; `customer_profile` 1:1 cho Customer; `staff_branch_assignment` lưu branch scope có thời hạn cho Branch Manager/Branch Staff; Guest là actor ẩn danh không có account.\n- **Rationale**: Một nguồn xác thực làm session, audit và foreign key vận hành nhất quán; Admin đổi assignment sẽ có hiệu lực ở request kế tiếp.\n- **Trade-offs**: Mỗi account có một role trong phạm vi hiện tại; nếu cần đa role phải revalidate Req 13 và filter.\n- **Follow-up**: Seed đủ bốn account role đăng nhập và kiểm thử assignment ACTIVE/ENDED trên SQL Server.\n\n### Decision: Không xây engine giảm giá hợp nhất');
}
r = r.replace(/MySQL SQL Server row-locking/g, 'Microsoft SQL Server row-locking');
fs.writeFileSync(rpath, r);
console.log('research.md updated');
NODE